## Starting - auto-generated by ../managed-cluster/managed-cluster from ../terraform-module-flux/variables.tf
variable "flux_version" {
  description = "Flux version to install"
  type        = string
  default     = "v0.15.3"
}

variable "flux_namespace" {
  description = "Namespace to install flux"
  type        = string
  default     = "flux-system"
}

variable "flux_git_repo" {
  description = "Git repository URL. Empty to ignore."
  type        = string
  default     = ""
}

variable "flux_git_repository_template" {
  description = "GitRepository template file."
  type        = string
  default     = "flux-git-repository.yaml.tpl"
}

variable "flux_git_repository_name" {
  description = "Name for GitRepository object"
  type        = string
  default     = "cluster"
}

variable "flux_manifests_path" {
  description = "Manifests dir inside GitRepository"
  type        = string
  default     = ""
}

variable "flux_wait" {
  description = "Wait for all manifests to apply"
  type        = bool
  default     = true
}

variable "flux_reconcile_interval" {
  description = "Reconcile interval for GitRepository"
  type        = string
  default     = "5m"
}

variable "flux_identity_file" {
  description = "SSH deploy private key"
  type        = string
  default     = "identity"
}

variable "flux_identity_pub_file" {
  description = "SSH deploy public key"
  type        = string
  default     = "identity.pub"
}

variable "flux_known_hosts_file" {
  description = "SSH known hosts file"
  type        = string
  default     = "known_hosts"
}

variable "flux_manifests_template_vars" {
  description = "Template vars for use by cluster manifests"
  type        = any
  default     = {}
}
## Finished - auto-generated by ../managed-cluster/managed-cluster from ../terraform-module-flux/variables.tf
