## Starting - auto-generated by ../managed-cluster/managed-cluster from ../terraform-module-cronitor/variables.tf
variable "cronitor_cluster_name" {
  description = "Cluster name"
  type        = string
}

variable "cronitor_customer_name" {
  description = "Customer name (Informative only)"
  type        = string
}

variable "cronitor_suffix" {
  description = "Customer name suffix (Informative only)"
  type        = string
  default     = ""
}

variable "cronitor_tags" {
  description = "Monitor tags (Informative only)"
  type        = list(string)
  default     = []
}

variable "cronitor_api_endpoint" {
  description = "Kubernetes API endpoint (Informative only)"
  type        = string
  default     = ""
}

variable "cronitor_api_key" {
  description = "Cronitor API key. Leave empty to destroy"
  type        = string
  default     = ""
}

variable "cronitor_notification_lists" {
  description = "Cronitor Notification Lists to send alerts"
  type        = list(string)
  default     = ["default"]
}

variable "cronitor_pagerduty_key" {
  description = "Cronitor PagerDuty key"
  type        = string
  default     = ""
}

variable "cronitor_timezone" {
  description = "Monitor Timezone"
  type        = string
  default     = "America/Sao_Paulo"
}

variable "cronitor_rule_timeout_minutes" {
  description = "Time in minutes cronitor waits before issuing an alert"
  type        = number
  default     = 5
}

variable "cronitor_rule_type" {
  description = "Rule alerting type"
  type        = string
  default     = "run_ping_not_received"
}
## Finished - auto-generated by ../managed-cluster/managed-cluster from ../terraform-module-cronitor/variables.tf
